name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch: # Allow manual triggering

env:
  PREFIX: $(HOME)/.local

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache apt packages
        uses: actions/cache@v3
        id: apt-cache
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-xorg-${{ hashFiles('.github/workflows/ci.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-xorg-
            ${{ runner.os }}-apt-

      - name: Build
        run: |
          make -j$(nproc) || exit 1

      - name: Install
        run: |
          make install || exit 1
